stages:
  - format

black-format:
  stage: format
  image: python:3.12
  script:
    - pip install black
    - black --line-length 120 --target-version py312 .
    - |
      if git diff --quiet; then
        echo "No formatting needed"
      else
        git config user.name "GitLab CI"
        git config user.email "gitlab-ci@example.com"
        git commit -am "Format code with Black"
        git push https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_PROJECT_URL#https://} HEAD:$CI_COMMIT_REF_NAME
      fi
  only:
    refs:
      - main
    changes:
      - "**/*.py"

prettier-format:
  stage: format
  image: node:lts
  script:
    - npm install --global prettier
    - prettier --write "**/*.{js,jsx,ts,tsx,json,css,scss,md,yml}"
    - |
      if git diff --quiet; then
        echo "No formatting needed"
      else
        git config user.name "GitLab CI"
        git config user.email "gitlab-ci@example.com"
        git commit -am "Format code with Prettier"
        git push https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_PROJECT_URL#https://} HEAD:$CI_COMMIT_REF_NAME
      fi
  only:
    refs:
      - main
    changes:
      - "**/*.{js,jsx,ts,tsx,json,css,scss,md,yml}"
