-- Create Databases
CREATE DATABASE IF NOT EXISTS prod;
CREATE DATABASE IF NOT EXISTS dev;

-- Create Users

CREATE USER IF NOT EXISTS 'prod_user'@'20.20.0.%' IDENTIFIED BY 'PROD_USER_PASSWORD' REQUIRE SSL;
GRANT ALL PRIVILEGES ON prod.* TO 'prod_user'@'20.20.0.%';

CREATE USER IF NOT EXISTS 'access_user'@'%' IDENTIFIED BY 'ACCESS_USER_PASSWORD' REQUIRE SSL;
GRANT ALL PRIVILEGES ON prod.* TO 'access_user'@'%';

FLUSH PRIVILEGES;