version: '3.8'

services:
  the-student-master-backend:
    image: registry.gitlab.com/themastercollection/thestudentmaster:latest
    ports:
      - "8000:8001"
    environment:
      # Set environment variables for the FastAPI application
      - ENVIRONMENT=prod              
      - DB_HOST=172.17.0.2
      - DB_DATABASE=thestudentmaster_dev

    secrets:
      - the_student_master_db_user
      - the_student_master_db_password
      - the_student_master_db_cert_password
      - the_student_master_db_ca_cert
      - the_student_master_refresh_private_key.pem
      - the_student_master_refresh_public_key.pem
      - the_student_master_access_private_key.pem
      - the_student_master_access_public_key.pem
      - the_student_master_security_private_key.pem
      - the_student_master_security_public_key.pem
    volumes:
      - db_data:/var/lib/mysql  # Adjust this if needed (e.g., for database backups or persistent data)
    networks:
      - db_network

secrets:
  the_student_master_db_user:
    external: true
  the_student_master_db_password:
    external: true
  the_student_master_db_cert_password:
    external: true
  the_student_master_db_ca_cert:
    external: true  
  the_student_master_refresh_private_key.pem:
    external: true
  the_student_master_refresh_public_key.pem:
    external: true
  the_student_master_access_private_key.pem:
    external: true
  the_student_master_access_public_key.pem:
    external: true
  the_student_master_security_private_key.pem:
    external: true
  the_student_master_security_public_key.pem:
    external: true
  
networks:
  db_network:
    external: true