version: "3.8"

services:
  backend:
    image: registry.gitlab.com/themastercollection/thestudentmaster:beta
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      # Set environment variables for the FastAPI application
      - ENVIRONMENT=prod
      - DB_HOST=mariadb
      - DB_DATABASE=prod
      - DB_USER=prod_user

    secrets:
      - tsm_db_password
      - tsm_db_cert
      - tsm_db_key
      - tsm_db_cert_password
      - tsm_mariadb_ca_cert
      - tsm_refresh_private_key
      - tsm_refresh_public_key
      - tsm_access_private_key
      - tsm_access_public_key
      - tsm_security_private_key
      - tsm_security_public_key
    networks:
      - tsm_db_network
      - tsm_shared_overlay
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8001:8001"

  mariadb:
    image: registry.gitlab.com/themastercollection/thestudentmaster:mariadb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - tsm_db_network
    secrets:
      - tsm_db_root_password
      - tsm_dev_user_password
      - tsm_prod_user_password
      - tsm_schuetze1000_password
      - tsm_leonidas_maker_password
      - tsm_xxchillkroetexx_password
      - tsm_mariadb_ca_cert
      - tsm_mariadb_cert
      - tsm_mariadb_key
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/tsm_db_root_password
    volumes:
      - tsm_mariadb_data:/var/lib/mysql
    configs:
      - source: tsm_mariadb_init_sh
        target: /docker-entrypoint-initdb.d/01-init.sh
        mode: 0775
      - source: tsm_mariadb_init_users_sql
        target: /docker-entrypoint-initdb.d/02-init-users.sql
        mode: 0644
      - source: tsm_mariadb_config
        target: /etc/mysql/conf.d/my_custom.cnf
    ports:
      - "3306:3306"

secrets:
  tsm_db_password:
    external: true
  tsm_db_cert:
    external: true
  tsm_db_cert_password:
    external: true
  tsm_db_key:
    external: true
  tsm_backend_db_ca_cert:
    external: true
  tsm_refresh_private_key:
    external: true
  tsm_refresh_public_key:
    external: true
  tsm_access_private_key:
    external: true
  tsm_access_public_key:
    external: true
  tsm_security_private_key:
    external: true
  tsm_security_public_key:
    external: true
  tsm_db_root_password:
    external: true
  tsm_dev_user_password:
    external: true
  tsm_prod_user_password:
    external: true
  tsm_schuetze1000_password:
    external: true
  tsm_leonidas_maker_password:
    external: true
  tsm_xxchillkroetexx_password:
    external: true
  tsm_mariadb_ca_cert:
    external: true
  tsm_mariadb_cert:
    external: true
  tsm_mariadb_key:
    external: true

configs:
  tsm_mariadb_init_sh:
    external: true
  tsm_mariadb_init_users_sql:
    external: true
  tsm_mariadb_config:
    external: true

networks:
  tsm_db_network:
    driver: overlay
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/24
  tsm_shared_overlay:
    attachable: true
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24

volumes:
  tsm_mariadb_data:

